exports.RequestType = {
    REGISTRATION: "new_user",
    VERIFICATION: "verify",
    RESEND_VERIFICATION: "verify_resend",
    LOGIN: "login",
    REFRESH: "refresh_token",
    GET: "get_user",
    UPDATE: "update_user",
    insertUserId: "update_uuid",
    updateEmail: "update_email",
    updateEmailVerification: "update_email_verify",
    updateName: "update_name",
    updatePassword: "update_password",
    passwordReset: "account_recovery",
    confirmPasswordReset: "confirm_account_recovery",
    LOGOUT: "logout",
    DELETE: "delete",
}